version: "3.8"
services:
  db:
    platform: linux/arm64/v8
    image: mysql
    volumes:
      - data:/var/lib/mysql
    env_file:
      - ./env/mysql.env
    
  backend:
    platform: linux/arm64/v8
    build: ./backend
    depends_on:
      - db
    ports:
      - "6788:6788"
      - "35729:35729"
      - "5005:5005"
    volumes:
        - ./backend/src:/app/src
    working_dir: /app
    command: sh run.sh
    env_file:
      - ./env/mysql.env
    
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend

  

  adminer:
    image: adminer
    ports:
      - "3003:8080"
    depends_on:
      - db

volumes:
    data:
