version: "3.8"
services:
#  backend:
#    build: ./backend
#    #    build:
#    #      context: ./backend
#    #      dockerfile: Dockerfile
#    ports:
#      - "81:80"
#    volumes:
#      - logs:/app/logs
#      - ./backend:/app
#      - /app/node_modules
#    env_file:
#      - ./env/backend.env
#    depends_on:
#      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend

  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    #    environment:
    #      - MONGO_INITDB_ROOT_USERNAME=root
    #      - MONGO_INITDB_ROOT_PASSWORD=root
    env_file:
      - ./env/mongo.env

volumes:
  data:
  logs:
